### ISSUE TITLE
Fix installation instructions & sample .eslintrc

### ISSUE THREAD

**Issue by kerrishotts** [adobe/eslint-plugin-twist#4]
Documentation says:

```
npm install @twist/eslint-plugin --save-dev
```

but this fails. Instead `npm install @twist/eslint-plugin-core` works.

Also, there's a missing comma in the sample .eslintrc after `extends` and before `parserOptions`.

**Comment by lanther** [comment]
Fixed.

@kerrishotts FYI, the syntax for auto-closing issues is pretty restrictive, so so if you just write "fix #4" it'll auto-close, but "fix issue #4" doesn't (putting extra words between the keyword and the issue number confuses it).
